# Generated by Django 5.0.1 on 2024-02-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporte_01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('licencia', models.CharField(max_length=200)),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte_01.transporte')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'Conductor',
            },
        ),
    ]
