# Generated by Django 5.0.1 on 2024-02-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar_extraccion', models.CharField(max_length=200)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pureza', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'Mineral',
                'verbose_name_plural': 'Minerales',
                'db_table': 'Mineral',
            },
        ),
    ]
