# Generated by Django 5.0.1 on 2024-02-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destino_02', '0001_initial'),
        ('mineria_00', '0001_initial'),
        ('transporte_01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('cantidad_mineral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destino_02.destino')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mineria_00.mineral')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte_01.transporte')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'db_table': 'Envio',
            },
        ),
    ]
