# Generated by Django 5.0.1 on 2024-01-29 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar_extraccion', models.CharField(max_length=200)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pureza', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=200)),
                ('tipo_transporte', models.CharField(max_length=200)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_mantenimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('cantidad_mineral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.destino')),
                ('mineral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mineral')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(max_length=200)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.envio')),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('licencia', models.CharField(max_length=200)),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.transporte')),
            ],
        ),
    ]
