# Generated by Django 5.0.1 on 2024-02-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='mineral',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='transporte',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='envio',
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.DeleteModel(
            name='Mineral',
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.DeleteModel(
            name='Inspeccion',
        ),
    ]
