# Generated by Django 5.0.1 on 2024-02-06 06:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0002_remove_envio_destino_remove_envio_mineral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'gestion',
                'verbose_name_plural': 'gestiones',
                'db_table': 'gestion',
            },
        ),
    ]
