# Generated by Django 5.0.1 on 2024-02-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
