# Generated by Django 5.0.1 on 2024-02-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_gestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='image',
            field=models.ImageField(upload_to='gestion_img'),
        ),
    ]
