# Generated by Django 5.0.1 on 2024-02-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=200)),
                ('tipo_transporte', models.CharField(max_length=200)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_mantenimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'Transporte',
            },
        ),
    ]
