# Generated by Django 5.0.1 on 2024-02-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envio_03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(max_length=200)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envio_03.envio')),
            ],
            options={
                'verbose_name': 'Inspeccion',
                'verbose_name_plural': 'Inspecciones',
                'db_table': 'Inspeccion',
            },
        ),
    ]
