# Generated by Django 5.0.1 on 2024-02-11 06:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion_05', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='resultado',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
